// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGEm4TmstEkz7XyzdVy7vnpyuIfhgaWmw',
    appId: '1:331446837054:web:5322d21cf513a2665dd66f',
    messagingSenderId: '331446837054',
    projectId: 'kiosk-7c531',
    authDomain: 'kiosk-7c531.firebaseapp.com',
    storageBucket: 'kiosk-7c531.firebasestorage.app',
    measurementId: 'G-1ET2LMS9Y5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJge8IlCvwjznIlZqtrhvhQhcPFZiDLNQ',
    appId: '1:331446837054:android:bc18e47617630b655dd66f',
    messagingSenderId: '331446837054',
    projectId: 'kiosk-7c531',
    storageBucket: 'kiosk-7c531.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABaz12quHYRwPdROP9yVTCiS5IBEcwhK4',
    appId: '1:331446837054:ios:1eedc1430d2026935dd66f',
    messagingSenderId: '331446837054',
    projectId: 'kiosk-7c531',
    storageBucket: 'kiosk-7c531.firebasestorage.app',
    iosBundleId: 'com.example.kioskApp',
  );
}
